### ISSUE TITLE
[tf_2dunet] fx plan initialize command is killed without any error

### ISSUE THREAD

**Issue by dskhanirfan** [intel/openfl#96] opened 2021-05-30 09:13 UTC
Hi I am following tf_2dunet on https://openfl.readthedocs.io/en/latest/running_the_federation.baremetal.html#creating-workspaces , However, fx plan initialize command is killed without any error. I have downloaded Brats data and added the data path in data.yaml file

**Comment by alexey-gruzdev** [comment] 2021-06-02 12:26
@dskhanirfan could we have more information about this issue? This is not typical behavior. Also we have upcoming fix related to [tf_2dunet] - Could you please reproduce this issue with [this PR](https://github.com/intel/openfl/pull/99)?

**Comment by stormvirux** [comment] 2021-07-13 18:40
@dskhanirfan I had the same issue when using `HGG`. I found that this happens when you don't have enough memory (RAM). I had 8GB and it was depleted quickly and it crashes without any error. You can notice this if you monitor RAM consumption using `htop` . `LGG` works without any issue.

**Comment by alexey-gruzdev** [comment] 2021-07-14 09:56
@stormvirux thanks for the info! That helps:) I am closing this since that a matter of resources rather than framework itself.

**Closed as completed by alexey-gruzdev** 2021-07-14 09:56 UTC
Labels: question
