### ISSUE TITLE
 DefaultCPUAllocator: can't allocate memory: you tried to allocate 451477504 bytes. 

### ISSUE THREAD

**Issue by YasirArfat32** [intel/openfl#102] opened 2021-06-03 17:53 UTC
**Describe the bug**
The collaborator gives the following error `EXCEPTION : [enforce fail at CPUAllocator.cpp:65] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 451477504 bytes. Error code 12 (Cannot allocate memory)` while running the '[New Interactive Python API (experimental) notebook](https://github.com/intel/openfl/blob/develop/openfl-tutorials/interactive_api_tutorials_(experimental)/Pytorch_Kvasir_UNET_workspace/new_python_api_UNET.ipynb)' (Pytorch using kvasir dataset). 
After successfully running round 0, the collaborators receive the new weights from the aggregator and one of the collaborators crashes with the above error. Even though we have checked our RAM and disk memory, it was sufficient before this exception.

**To Reproduce**
Steps to reproduce the behaviour:
1. We are running Aggregator and 2 Collaborators on distributed machines. 
2. On Aggregator we run the python code interactively
2. On Collaborator1 we run this command `fx collaborator start -d data.yaml -n one`
3. On Collaborator2 we run this command `fx collaborator start -d data.yaml -n two`

**Expected behavior**
The model should run more rounds.

**Screenshots**

<img width="1427" alt="Screen1" src="https://user-images.githubusercontent.com/12051191/120689126-0f947400-c4a4-11eb-9805-4201d098e1a0.png">

**Desktop (please complete the following information):**
 - OS: [ubuntu]
 - Browser [18.04]
 - Version [Python 3.7.6]
 - OpenFL Version [1.1]

**Comment by igor-davidyuk** [comment] 2021-06-07 08:06
Hello, @YasirArfat32!
Thank you for reporting the problem.
Have you tried to reproduce this issue on another machine? I am asking because I have never faced such a problem.

**Comment by alexey-gruzdev** [comment] 2021-07-08 17:42
@YasirArfat32 any update on this subj? Have you tried to reproduce the same behavior on another machine?

**Comment by alexey-gruzdev** [comment] 2021-07-12 12:35
@YasirArfat32 I would close this issue, so if you still face this behavior and can reproduce it with develop branch & other machine, let us know!:)

**Closed as completed by alexey-gruzdev** 2021-07-12 12:35 UTC
