### ISSUE TITLE
tf_2dunet Exception 

### ISSUE THREAD

**Issue by omnia487** [intel/openfl#398] opened 2022-03-25 11:57 UTC
trying to initialize the tf_2dunet plan but I cant 
Exception : need at least one array to concatenate 
![156519762-74d24fc0-752d-499b-b402-31c2e318bcd2](https://user-images.githubusercontent.com/89255896/160116555-86ae7ea3-0bb8-4da9-acac-aeefeb65ea89.png)

**Comment by itrushkin** [comment] 2022-03-25 13:03
Hey @omnia487. Thank you for your interest in OpenFL!

Your question looks like a duplicate of #366.
>Because of legal restriction of [BraTS dataset](https://www.med.upenn.edu/cbica/brats2019/data.html), tf_2dunet  workspace requires data to be already on the device. If you have the data locally, could you provide directory tree of the dataset?
You can do it via executing:
>
>     sudo apt-get install tree
>     tree -L 2 path/to/data/MICCAI_BraTS_2019_Data_Training/HGG # replace with your location

**Comment by omnyaatef22** [comment] 2022-03-26 08:15
![1](https://user-images.githubusercontent.com/98268106/160230985-43edca1a-9711-496c-b6bc-dab44ce667ec.PNG)
![2](https://user-images.githubusercontent.com/98268106/160230987-d0c07503-09cb-446f-99c0-39028c889c54.PNG)
![3](https://user-images.githubusercontent.com/98268106/160230988-15f05e22-7def-421d-94c1-222782bff4d7.PNG)
![4](https://user-images.githubusercontent.com/98268106/160230990-20adb115-4bc4-47a3-97f8-4dd090cd50a8.PNG)
![5](https://user-images.githubusercontent.com/98268106/160230991-a7dc4b97-4256-4550-a581-e32bc88cd359.PNG)

**Comment by theakshaypant** [comment] 2024-12-10 14:50
The example was updated recently and can be run using the steps mentioned in https://github.com/securefederatedai/openfl/issues/1126#issuecomment-2507136408 after changes introduced in #1178. 

Could you check if the error can be reproduced or can this issue be closed.

**Comment by teoparvanov** [comment] 2024-12-13 08:14
PS: this workspace is being fundamentally reworked and migrated to the Keras 3 API as part of [this PR](https://github.com/securefederatedai/openfl/pull/1174), where it has been renamed to `keras_2dunet`. Please retest, and let us know if you still encounter any issues.

**Closed as completed** 2024-12-13 08:13 UTC
Labels: question
