### ISSUE TITLE
Elaborate docs on TaskRunner interface

### ISSUE THREAD

**Issue by igor-davidyuk** [intel/openfl#608] opened 2022-11-20 06:52 UTC
We have the TaskRunner interface is scarcely described in docs, adding details would make it more transparent for users. Specifically, I received questions regarding `FL task` methods signatures.

**Comment by JacobGlennAyers** [comment] 2023-08-16 21:30
As a user that is encountering issues related to the flexibility of the existing TaskRunner classes and finding it to be very challenging to integrate desired models and training pipelines, this would be much appreciated.

**Comment by teoparvanov** [comment] 2024-11-04 12:34
Closing as a duplicate of https://github.com/securefederatedai/openfl/issues/521

**Closed as completed by teoparvanov** 2024-11-04 12:34 UTC
Labels: documentation
