### ISSUE TITLE
RuntimeError while training and validating on different devices

### ISSUE THREAD

**Issue by itrushkin** [intel/openfl#298] opened 2022-01-21 13:26 UTC
**The Bug**
Training and validation tasks could not be executed on different devices.
The current device assigning policy does not allow specifying devices per task, but if the device is overridden inside a task code (e.g. for CPU inference), an error is raised (see below).

**Steps To Reproduce**
1. Open any tutorial folder in `openfl-tutorials/interactive_api`. I found the bug in `PyTorch_Kvasir_UNet`.
2. Create and activate `director` Python environment.
3. Execute:
    ```
    pip install /path/to/openfl
    cd director
    bash start_director.sh
    ``` 
4. In a separate terminal create and activate `envoy` Python environment.
5. Execute:
    ```
    pip install /path/to/openfl
    cd envoy
    pip install sd_requirements.txt
    bash start_envoy.sh
    ```
3. In a separate terminal create and activate `workspace` Python environment.
4. Execute:
    ```
    pip install /path/to/openfl
    pip install torchvision==0.8.1 # for Kvasir workspace
    jupyter notebook
    ```
5. Open the Jupyter UI and go to the main experiment notebook in the `workspace` folder.
6. In tasks definition, add a device overriding line so devices for different tasks differ. Since for Kvasir example `CUDA_PREFERRED` policy is set, all tasks get `cuda:*` devices in parameters. So we need to change it to `cpu`:
    ```python
    @TI.register_fl_task(model='unet_model', data_loader='val_loader', device='device')     
    def validate(unet_model, val_loader, device):
        device='cpu'  #  HERE WE OVERRIDE THE DEVICE
        print(f'\n\n TASK VALIDATE GOT DEVICE {device}\n\n')
    
        unet_model.eval()
        unet_model.to(device)
    
        val_loader = tqdm.tqdm(val_loader, desc="validate")

        val_score = 0
        total_samples = 0

        with torch.no_grad():
            for data, target in val_loader:
                samples = target.shape[0]
                total_samples += samples
                data, target = torch.tensor(data).to(device), \
                    torch.tensor(target).to(device, dtype=torch.int64)
                output = unet_model(data)
                val = soft_dice_coef(output, target)
                val_score += val.sum().cpu().numpy()
                
        return {'dice_coef': val_score / total_samples,}
    ```
7. Run all cells.
8. During `fl_experiment.stream_metrics()` an error occurs:
    ```
    [15:53:29] ERROR    Collaborator failed with error: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!:  envoy.py:75
                    Traceback (most recent call last):                                                                                                          
                      File "/home/itrushkin/.virtualenvs/envoy/lib/python3.8/site-packages/openfl/component/envoy/envoy.py", line 73, in run                    
                        self._run_collaborator()                                                                                                                
                      File "/home/itrushkin/.virtualenvs/envoy/lib/python3.8/site-packages/openfl/component/envoy/envoy.py", line 141, in                       
                    _run_collaborator                                                                                                                           
                        col.run()                                                                                                                               
                      File "/home/itrushkin/.virtualenvs/envoy/lib/python3.8/site-packages/openfl/component/collaborator/collaborator.py", line 145,            
                    in run                                                                                                                                      
                        self.do_task(task, round_number)                                                                                                        
                      File "/home/itrushkin/.virtualenvs/envoy/lib/python3.8/site-packages/openfl/component/collaborator/collaborator.py", line 241,            
                    in do_task                                                                                                                                  
                        global_output_tensor_dict, local_output_tensor_dict = func(                                                                             
                      File "/home/itrushkin/.virtualenvs/envoy/lib/python3.8/site-packages/openfl/federated/task/task_runner.py", line 129, in                  
                    collaborator_adapted_task                                                                                                                   
                        metric_dict = callable_task(**task_kwargs)                                                                                              
                      File                                                                                                                                      
                    "/home/itrushkin/.virtualenvs/openfl_research/lib/python3.8/site-packages/openfl/interface/interactive_api/experiment.py", line             
                    436, in wrapper_decorator                                                                                                                   
                        metric_dict = training_method(**task_keywords)                                                                                          
                      File "<ipython-input-13-b3468c8701fc>", line 50, in train                                                                                 
                      File "/home/itrushkin/.virtualenvs/envoy/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in                            
                    decorate_context                                                                                                                            
                        return func(*args, **kwargs)                                                                                                            
                      File "/home/itrushkin/.virtualenvs/envoy/lib/python3.8/site-packages/torch/optim/adam.py", line 108, in step                              
                        F.adam(params_with_grad,                                                                                                                
                      File "/home/itrushkin/.virtualenvs/envoy/lib/python3.8/site-packages/torch/optim/functional.py", line 86, in adam                         
                        exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)                                                                                         
                    RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
    ```
**Expected behavior**
Training is completed without errors.

**Desktop**
OS: Ubuntu 18.04
Python: 3.8
CUDA: 11.2
PyTorch: 1.7.0

**Comment by mansishr** [comment] 2022-03-08 18:44
Reproduced this behavior on MXNet. We should add model.collect_params().reset_ctx(ctx=[device]) to the tutorial when we change devices to reset the context.
Could not reproduce this behavior for Tensorflow example. The user can switch devices for different tasks without an issue in Tensorflow.

**Comment by alexey-gruzdev** [comment] 2022-03-09 07:31
cc @alexey-khorkin @ViktoriiaRomanova

**Comment by igor-davidyuk** [comment] 2022-03-14 08:50
Did you try to move the optimizer to CPU?

**Comment by igor-davidyuk** [comment] 2022-03-25 12:23
You should use the assigned device in your task

**Comment by alexey-gruzdev** [comment] 2022-03-25 12:38
After internal discussion, we close this due to creation of more general problem statement in https://github.com/intel/openfl/issues/399.

**Closed as completed by alexey-gruzdev** 2022-03-25 12:38 UTC
Labels: bug
