### ISSUE TITLE
Can’t use custom loss or metrics in Director-Based workflow

### ISSUE THREAD

**Issue by sky712345678** [intel/openfl#451] opened 2022-07-01 13:12 UTC
**Describe the bug**
Can’t use custom loss or metrics to train a model with `tf.keras.Model` APIs in Director-Based workflow.

Configurations:
- OpenFL workflow: Director-Based
- Model to train: 3D U-Net
- Loss function: dice loss
- Metric: dice coefficient

I was training 3D U-Net with OpenFL. The loss function I used is dice loss.
To improve the training performance on Intel Xeon CPUs, I compiled my model with `tf.keras.Model.compile()` and did the training task with `tf.keras.Model.fit()`. These methods execute my model in “graph execution mode”, improving the training performance in Director-Based workflow. This is the training task:
```ruby
# Register FL training task
@TI.register_fl_task(model='model', data_loader='data_loader', device='device', optimizer='optimizer')
def train(model, data_loader, device, optimizer, loss_fn=loss_fn):
    history = model.fit(data_loader, epochs=1, verbose=1)
    
    return dict(zip(['loss'], [np.mean([history.history['loss']])]))
```

However, I couldn’t use the custom loss function, dice loss, in this approach. The collaborator failed with the error:  
`Unknown loss function: dice loss`
```
           INFO     🧿 Starting a Collaborator Service.                                                                                             envoy.py:159
           INFO     Building 🡆 Object CloudpickleSerializer from openfl.plugins.interface_serializer.cloudpickle_serializer Module.                  plan.py:173
           ERROR    Collaborator failed with error: Unknown loss function: dice_loss. Please ensure this object is passed to the `custom_objects`    envoy.py:93
                    argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.:                         
```

I also tried disabling `__reduce__` override on `tf.keras.Model`, but the collaborator keeps failing.

To use the custom loss function, I must define it in `keras_adapter.py` on the director. Then, the collaborator will know what dice loss is and start training. The code will be like this:

```ruby
class FrameworkAdapterPlugin(FrameworkAdapterPluginInterface):
    """Framework adapter plugin class."""

    def __init__(self) -> None:
        """Initialize framework adapter."""
        pass

    @staticmethod
    def serialization_setup():
        """Prepare model for serialization (optional)."""
        # Source: https://github.com/tensorflow/tensorflow/issues/34697
        import tensorflow as tf
        from tensorflow.keras.models import Model
        from tensorflow.python.keras.layers import deserialize
        from tensorflow.python.keras.layers import serialize
        from tensorflow.python.keras.saving import saving_utils

        # MODIFICATIONS
        def dice_coef(target, prediction, axis=(1, 2, 3), smooth=0.0001):
            """
            Sorenson Dice
            \frac{  2 \times \left | T \right | \cap \left | P \right |}{ \left | T \right | +  \left | P \right |  }
            where T is ground truth mask and P is the prediction mask
            """
            prediction = tf.round(prediction)  # Round to 0 or 1

            intersection = tf.reduce_sum(target * prediction, axis=axis)
            union = tf.reduce_sum(target + prediction, axis=axis)
            numerator = tf.constant(2.) * intersection + smooth
            denominator = union + smooth
            coef = numerator / denominator

            return tf.reduce_mean(coef)
        
        # MODIFICATIONS
        def dice_loss(target, prediction, axis=(1, 2, 3), smooth=0.0001):
            """
            Sorenson (Soft) Dice loss
            Using -log(Dice) as the loss since it is better behaved.
            Also, the log allows avoidance of the division which
            can help prevent underflow when the numbers are very small.
            """
            intersection = tf.reduce_sum(prediction * target, axis=axis)
            p = tf.reduce_sum(prediction, axis=axis)
            t = tf.reduce_sum(target, axis=axis)
            numerator = tf.reduce_mean(intersection + smooth)
            denominator = tf.reduce_mean(t + p + smooth)
            dice_loss = -tf.math.log(2.*numerator) + tf.math.log(denominator)

            return dice_loss

        def unpack(model, training_config, weights):
            restored_model = deserialize(model)

            # MODIFICATIONS
            custom_obj = {'dice_loss': dice_loss, 'dice_coef': dice_coef}

            if training_config is not None:
                restored_model.compile(
                    **saving_utils.compile_args_from_training_config(
                        training_config, custom_objects=custom_obj    # MODIFICATIONS
                    )
                )
            restored_model.set_weights(weights)
            return restored_model
```

**To Reproduce**
[custom_loss_error.zip](https://github.com/intel/openfl/files/9028744/custom_loss_error.zip)
1. Reproduce the error: 
(1) Download `custom_loss_error.zip` and unzip it
(2) Start the director with the config file in `director` folder
`> fx director start --disable-tls -c director.yaml`
(3) Start the envoy with the config file and the shard descriptor in `envoy` folder
`> fx envoy start -n NAME --disable-tls --envoy-config-path envoy_config.yaml -dh HOSTNAME -dp 54003`
(4) Start experiment with the Jupyter notebook and model definition in `workspace` folder
`> jupyter lab`
(5) Run all Jupyter notebook cells to start the experiment
---
2. Use custom loss function for training tasks:
(1) Open keras_adapter.py in `openfl/plugins/frameworks_adapters` folder
(2) Modify `keras_adapter.py`...
```ruby
class FrameworkAdapterPlugin(FrameworkAdapterPluginInterface):
    """Framework adapter plugin class."""

    def __init__(self) -> None:
        """Initialize framework adapter."""
        pass

    @staticmethod
    def serialization_setup():
        """Prepare model for serialization (optional)."""
        # Source: https://github.com/tensorflow/tensorflow/issues/34697
        import tensorflow as tf
        from tensorflow.keras.models import Model
        from tensorflow.python.keras.layers import deserialize
        from tensorflow.python.keras.layers import serialize
        from tensorflow.python.keras.saving import saving_utils

        # MODIFICATIONS
        def dice_coef(target, prediction, axis=(1, 2, 3), smooth=0.0001):
            """
            Sorenson Dice
            \frac{  2 \times \left | T \right | \cap \left | P \right |}{ \left | T \right | +  \left | P \right |  }
            where T is ground truth mask and P is the prediction mask
            """
            prediction = tf.round(prediction)  # Round to 0 or 1

            intersection = tf.reduce_sum(target * prediction, axis=axis)
            union = tf.reduce_sum(target + prediction, axis=axis)
            numerator = tf.constant(2.) * intersection + smooth
            denominator = union + smooth
            coef = numerator / denominator

            return tf.reduce_mean(coef)
        
        # MODIFICATIONS
        def dice_loss(target, prediction, axis=(1, 2, 3), smooth=0.0001):
            """
            Sorenson (Soft) Dice loss
            Using -log(Dice) as the loss since it is better behaved.
            Also, the log allows avoidance of the division which
            can help prevent underflow when the numbers are very small.
            """
            intersection = tf.reduce_sum(prediction * target, axis=axis)
            p = tf.reduce_sum(prediction, axis=axis)
            t = tf.reduce_sum(target, axis=axis)
            numerator = tf.reduce_mean(intersection + smooth)
            denominator = tf.reduce_mean(t + p + smooth)
            dice_loss = -tf.math.log(2.*numerator) + tf.math.log(denominator)

            return dice_loss

        def unpack(model, training_config, weights):
            restored_model = deserialize(model)

            # MODIFICATIONS
            custom_obj = {'dice_loss': dice_loss, 'dice_coef': dice_coef}

            if training_config is not None:
                restored_model.compile(
                    **saving_utils.compile_args_from_training_config(
                        training_config, custom_objects=custom_obj    # MODIFICATIONS
                    )
                )
            restored_model.set_weights(weights)
            return restored_model
```
(3) Download `custom_loss_error.zip` and unzip it
(4) Start the director with the config file in `director` folder
`> fx director start --disable-tls -c director.yaml`
(5) Start the envoy with the config file and the shard descriptor in `envoy` folder
`> fx envoy start -n NAME --disable-tls --envoy-config-path envoy_config.yaml -dh HOSTNAME -dp 54003`
(6) Start experiment with the Jupyter notebook and model definition in `workspace` folder
`> jupyter lab`
(7) Run all Jupyter notebook cells to start the experiment

**Expected behavior**
Custom loss functions should be deserialized correctly on the envoy (or collaborator) and the training runs smoothly.

**Screenshots**
![custom_loss_error_screenshot](https://user-images.githubusercontent.com/37875281/176892956-75fcde32-df2e-424f-a727-0b3de85844c0.png)

**Desktop (please complete the following information):**
- OS: Ubuntu 18.04
- Python: 3.7.5
- OpenFL: 1.3
- TensorFlow: 2.7.0

**Additional context**
The dataset I used is private, I couldn’t share it at this moment. Thus, the shard descriptor in `custom_loss_error.zip` generates random data to simulate the workflow and reproduce the error.

Traceback of the error:
```
           INFO     🧿 Starting a Collaborator Service.                                                                                             envoy.py:159
           INFO     Building 🡆 Object CloudpickleSerializer from openfl.plugins.interface_serializer.cloudpickle_serializer Module.                  plan.py:173
           ERROR    Collaborator failed with error: Unknown loss function: dice_loss. Please ensure this object is passed to the `custom_objects`    envoy.py:93
                    argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.:                         
                    Traceback (most recent call last):                                                                                                          
                      File "/home/user/Desktop/Github/director_CM/venv/lib/python3.7/site-packages/openfl/component/envoy/envoy.py", line 91, in run            
                        self._run_collaborator()                                                                                                                
                      File "/home/user/Desktop/Github/director_CM/venv/lib/python3.7/site-packages/openfl/component/envoy/envoy.py", line 162, in               
                    _run_collaborator                                                                                                                           
                        self.certificate, shard_descriptor=self.shard_descriptor)                                                                               
                      File "/home/user/Desktop/Github/director_CM/venv/lib/python3.7/site-packages/openfl/federated/plan/plan.py", line 448, in                 
                    get_collaborator                                                                                                                            
                        model_provider, task_keeper, data_loader = self.deserialize_interface_objects()                                                         
                      File "/home/user/Desktop/Github/director_CM/venv/lib/python3.7/site-packages/openfl/federated/plan/plan.py", line 554, in                 
                    <genexpr>                                                                                                                                   
                        return (self.restore_object(api_layer['settings'][filename]) for filename in filenames)                                                 
                      File "/home/user/Desktop/Github/director_CM/venv/lib/python3.7/site-packages/openfl/federated/plan/plan.py", line 574, in                 
                    restore_object                                                                                                                              
                        obj = serializer_plugin.restore_object(filename)                                                                                        
                      File "/home/user/Desktop/Github/director_CM/venv/lib/python3.7/site-packages/openfl/plugins/interface_serializer/cloudpickle_s            
                    erializer.py", line 27, in restore_object                                                                                                   
                        return cloudpickle.load(f)                                                                                                              
                      File                                                                                                                                      
                    "/home/user/Desktop/Github/director_DM/venv/lib/python3.7/site-packages/openfl/plugins/frameworks_adapters/keras_adapter.py",               
                    line 28, in unpack                                                                                                                          
                        training_config                                                                                                                         
                      File "/home/user/Desktop/Github/director_CM/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/saving_utils.py",             
                    line 213, in compile_args_from_training_config                                                                                              
                        loss = _deserialize_nested_config(losses.deserialize, loss_config)                                                                      
                      File "/home/user/Desktop/Github/director_CM/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/saving_utils.py",             
                    line 254, in _deserialize_nested_config                                                                                                     
                        return deserialize_fn(config)                                                                                                           
                      File "/home/user/Desktop/Github/director_CM/venv/lib/python3.7/site-packages/tensorflow/python/keras/losses.py", line 2109, in            
                    deserialize                                                                                                                                 
                        printable_module_name='loss function')                                                                                                  
                      File "/home/user/Desktop/Github/director_CM/venv/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py",             
                    line 709, in deserialize_keras_object                                                                                                       
                        .format(printable_module_name, object_name))                                                                                            
                    ValueError: Unknown loss function: dice_loss. Please ensure this object is passed to the `custom_objects` argument. See                     
                    https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.                                        
           INFO     Send WaitExperiment request                                                                                            director_client.py:80
           INFO     WaitExperiment response has received                                                                                   director_client.py:82
```

**Comment by MasterSkepticista** [comment] 2022-07-02 05:08
@sky712345678 This looks like a serialization issue.

Tensorflow 2.7 had issues supporting native serialization and requiring overrides on `__reduce__`. This was fixed in later Tensorflow releases https://github.com/keras-team/keras/pull/14748.

Can you quickly check if you see the same issue with Tensorflow 2.8 (with default adapter)? That will help us narrow down the issue.

**Comment by sky712345678** [comment] 2022-07-05 06:36
Hi @MasterSkepticista ,
After switching to TensorFlow 2.8 (or 2.9) with default adapter, I got the same issue in https://github.com/intel/openfl/issues/422. The collaborator failed with BatchNormalization layer.
```
           INFO     🧿 Starting a Collaborator Service.                                                                                             envoy.py:159
           INFO     Building 🡆 Object CloudpickleSerializer from openfl.plugins.interface_serializer.cloudpickle_serializer Module.                  plan.py:173
           ERROR    Collaborator failed with error: Unknown layer: BatchNormalization. Please ensure this object is passed to the `custom_objects`   envoy.py:93
                    argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.:                         
                    Traceback (most recent call last):                                                                                                          
                      File "/home/user/Desktop/Github/director_CM/venv/lib/python3.7/site-packages/openfl/component/envoy/envoy.py", line 91, in run            
                        self._run_collaborator()                                                                                                                
                      File "/home/user/Desktop/Github/director_CM/venv/lib/python3.7/site-packages/openfl/component/envoy/envoy.py", line 162, in               
                    _run_collaborator                                                                                                                           
                        self.certificate, shard_descriptor=self.shard_descriptor)                                                                               
                      File "/home/user/Desktop/Github/director_CM/venv/lib/python3.7/site-packages/openfl/federated/plan/plan.py", line 448, in                 
                    get_collaborator                                                                                                                            
                        model_provider, task_keeper, data_loader = self.deserialize_interface_objects()                                                         
                      File "/home/user/Desktop/Github/director_CM/venv/lib/python3.7/site-packages/openfl/federated/plan/plan.py", line 554, in                 
                    <genexpr>                                                                                                                                   
                        return (self.restore_object(api_layer['settings'][filename]) for filename in filenames)                                                 
                      File "/home/user/Desktop/Github/director_CM/venv/lib/python3.7/site-packages/openfl/federated/plan/plan.py", line 574, in                 
                    restore_object                                                                                                                              
                        obj = serializer_plugin.restore_object(filename)                                                                                        
                      File "/home/user/Desktop/Github/director_CM/venv/lib/python3.7/site-packages/openfl/plugins/interface_serializer/cloudpickle_s            
                    erializer.py", line 27, in restore_object                                                                                                   
                        return cloudpickle.load(f)                                                                                                              
                      File                                                                                                                                      
                    "/home/user/Desktop/Github/director_DM/venv/lib/python3.7/site-packages/openfl/plugins/frameworks_adapters/keras_adapter.py",               
                    line 24, in unpack                                                                                                                          
                        restored_model = deserialize(model)                                                                                                     
                      File "/home/user/Desktop/Github/director_CM/venv/lib/python3.7/site-packages/tensorflow/python/keras/layers/serialization.py",            
                    line 127, in deserialize                                                                                                                    
                        printable_module_name='layer')                                                                                                          
                      File "/home/user/Desktop/Github/director_CM/venv/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py",             
                    line 678, in deserialize_keras_object                                                                                                       
                        list(custom_objects.items())))                                                                                                          
                      File "/home/user/Desktop/Github/director_CM/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py",               
                    line 668, in from_config                                                                                                                    
                        config, custom_objects)                                                                                                                 
                      File "/home/user/Desktop/Github/director_CM/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py",               
                    line 1278, in reconstruct_from_config                                                                                                       
                        process_layer(layer_data)                                                                                                               
                      File "/home/user/Desktop/Github/director_CM/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py",               
                    line 1260, in process_layer                                                                                                                 
                        layer = deserialize_layer(layer_data, custom_objects=custom_objects)                                                                    
                      File "/home/user/Desktop/Github/director_CM/venv/lib/python3.7/site-packages/tensorflow/python/keras/layers/serialization.py",            
                    line 127, in deserialize                                                                                                                    
                        printable_module_name='layer')                                                                                                          
                      File "/home/user/Desktop/Github/director_CM/venv/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py",             
                    line 660, in deserialize_keras_object                                                                                                       
                        config, module_objects, custom_objects, printable_module_name)                                                                          
                      File "/home/user/Desktop/Github/director_CM/venv/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py",             
                    line 561, in class_and_config_for_serialized_keras_object                                                                                   
                        .format(printable_module_name, class_name))                                                                                             
                    ValueError: Unknown layer: BatchNormalization. Please ensure this object is passed to the `custom_objects` argument. See                    
                    https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.                                        
           INFO     Send WaitExperiment request                                                                                            director_client.py:80
           INFO     WaitExperiment response has received                                                                                   director_client.py:82
```
Not sure whether custom loss functions or metrics are deserialized correctly.

**Comment by mansishr** [comment] 2022-07-13 23:45
Hi @sky712345678, I was able to reproduce the error. I bumped the TF version to 2.8 and instead got this error: 

```
ValueError: Unable to restore custom object of type _tf_keras_metric. Please make sure that any custom layers are included in               
                    the `custom_objects` arg when calling `load_model()` and make sure that all layers implement `get_config` and `from_config`.
```
                    
For TF version 2.8 or above, `serialization_setup()` isn't called, so that's not the issue. The issue is that if custom objects are serialized, they need to be defined during deserialization/loading the model.  When you define custom loss as a part of the model, then during deserialization,  `cloudpickle` calls native keras `load_model()` which needs the definition of custom loss. Hence the [error](https://github.com/jakeret/unet/issues/8). 

A 'hacky' way that works: Don't used compiled model with `ModelInterface `class, instead put `model.compile(loss=loss_fn, optimizer=optimizer, loss_weights=[3], metrics=[dice_coef])` inside the train task before `model.fit()`. Compile defines the loss function, optimizer and metrics and [doesn't affect the weights in any way](https://stackoverflow.com/questions/47995324/does-model-compile-initialize-all-the-weights-and-biases-in-keras-tensorflow).

**Comment by sky712345678** [comment] 2022-07-17 17:19
Hi @mansishr ,
I forgot to mention, I also got the same `_tf_keras_metric` error with TensorFlow 2.8. It is because that I used custom metric `dice_coef` for the training.
Unset the argument `metrics` in `model.compile()` and the error of `_tf_keras_metric` should disappear.

I've tested the **hacky way** with 1 aggregator and 1 collaborator (run with 2 terminals). Putting `model.compile()` inside the train task did work. The model converged.
I think I will test it with more collaborators next. See if losing optimizer states influence the training process.

Also, if there are any better ways to solve the problem, please share with me. Thank you.

**Comment by teoparvanov** [comment] 2024-11-15 14:51
Closing this issue, as the Interactive API is being deprecated in favor of Workflow API.

**Closed as completed by teoparvanov** 2024-11-15 14:51 UTC
Labels: bug
